#! /bin/sh

#pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V 
#VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          9
bspc config top_padding		20
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focused_border_color "#d79921"
bspc config active_border_color "#1d2021"

killall polybar

sxhkd &

polybar example &

xrdb ~/.Xresources

feh --bg-fill ~/Wallpapers/foh0n427ez471.png

setxkbmap tr &

xsetroot -cursor_name left_ptr &


